# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the application code into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose the port your application will run on (if applicable)
EXPOSE 80

# Define any environment variables if needed
ENV ENV_NAME blue

# Command to run your application
CMD ["python", "app.py"]
